# Document:
# http://simiki.org/docs/configuration.html

url: 
title: Wiki | jinshuai86
keywords: Java,Operation System,Network,Tool
description: jinshuai's personal wiki
author: JinShuai
root: /wiki/
deploy:
  - type: git
